### ISSUE TITLE
Slight popping in audio sometimes

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/ADLMIDI-Player-Java#1] opened 2017-12-29 21:19 UTC
Hey, I compiled the sources as of today and tweaked the CMakefile a little bit for the ARM chip in my LG G6. However, even if I use your build or mine, sometimes there are pops and skips as if the buffer is being exhausted. Weird.

Any ideas? Or is this Android being Android?

**Comment by Wohlstand** [comment] 2017-12-29 22:39
Do you mean a choppy sound? This means that current implementation isn't optimal to play on slower devices. You will need device with 1.2 Ghz per every core power (as on SGS 3) to play without choppy sound. Anyway, to avoid choppy sound on slower devieces I need to change a playing strategy (currently I use OpenSL ES as experiment to reduce power eating, or I'll try to tweak around AudioTrack to use different buffer management strategy to avoid choppy playiback. This even will allow to use much more accurate Nuked OPL3 emulator that I wasn't used in mine build as it too powerful).

**Comment by sneakernets** [comment] 2017-12-31 09:00
There's the weird part, the LG G6  is a relatively new phone that's pretty fast.

**Comment by Wohlstand** [comment] 2017-12-31 12:08
Okay, I see your phonr has 2.35 Ghz frequency. And this is really weird... I'll try to use AudioTrack-based audio output with different strategy. Please try out VLC player and turn the OpenSL ES audio engine inside it's settimgs and try to play anything.

**Comment by sneakernets** [comment] 2017-12-31 20:27
Alright I'll try that.

**Comment by sneakernets** [comment] 2018-01-02 00:57
Yeahhh it's popping sometimes even on that. It's very noticeable if I have Facebook Messenger on (that resource hog!).

**Comment by Wohlstand** [comment] 2018-09-30 03:54
Try out the latest build now. Does it works stable or dying or playing choppy crap?

**Comment by freq-mod** [comment] 2018-10-01 10:15
Idk about @sneakernets but I can give my report
I have LG K10 - quadcore, 1.2 GhZ each, 1.5 GB RAM (terrible phone, I know)
Even with just 2 OPL cores I can hear what may be called "slight popping", it gets much worse at about 8 ~9 cores
I don't know why, but it stutters more when playing using 2x2op or 4op banks, no matter how many chips or 4op channels...
Tested on 1.4 release 
Does this player use DosBox emulator or rather this optimized Nuked 1.7 one?

**Comment by Wohlstand** [comment] 2018-10-01 12:46
My phone has 1.4 Ghz and also quad-core, and it has 800~1000 MB RAM (Samsung Galaxy S3 of 2013'th year), but with the update I have made, it's not works much more stable than in a past. However, yeah, I didn't tested on slower devices, and looks like 1.2 Ghz looks too slow. At me chops are also happens even with regular music player when playing regular PCM formats (OGG, WAV, MP3, FLAC, etc.).

On other side: I had to try out DOSBox OPL3 emulator on Windows 98 machine with 300 Mhz CPU (on 9x build of OPL3-BE), and looks it works fine with no chops.

**Comment by sneakernets** [comment] 2018-10-01 16:16
I now have a Note 9 (which has insane specs) so this shouldn't be that much of an issue *now*, but I will download a build and check it out.

**Comment by sneakernets** [comment] 2018-10-03 17:04
hey @Wohlstand can I get an updated build for this? I noticed some last-minute commits after the release.

**Comment by Wohlstand** [comment] 2018-10-03 17:05
It's better CI will build & deploy the stuff, but, lemme pull my build from phone to upload here...

**Comment by Wohlstand** [comment] 2018-10-03 17:22
[ADLMIDI-Player-release.apk.zip](https://github.com/Wohlstand/ADLMIDI-Player-Java/files/2443032/ADLMIDI-Player-release.apk.zip)

**Comment by sneakernets** [comment] 2018-10-03 18:20
Woohoo thank you! will test ASAP, new phone means no midi files right now 📱

**Comment by Wohlstand** [comment] 2018-10-03 18:58
Then, take mine, lemme give an url...

**Comment by Wohlstand** [comment] 2018-10-03 18:59
http://wohlsoft.ru/docs/Music/MIDI/
Here is some

**Comment by Wohlstand** [comment] 2019-01-15 22:21
@sneakernets , ping! :bell: 
Try the more fresh build from releases, do you have any issues with it or everything is fine? Try on different phones to be sure it will work on both...

**Comment by sneakernets** [comment] 2019-01-16 18:11
Sure! I'll try it. I just downloaded it today.

**Comment by freq-mod** [comment] 2019-01-16 18:13
Tested 1.4.2 release on Huawei Y5 2018 (1.5 GhZ quad-core CPU, 2GB RAM, Android 8.0). Weak phone, yet it's runs almost flawlessly, even on ~5 chips, no matter if it's 2-op or 4-op bank. It sometimes lags for a while on random occasions, but it's not a huge problem. No more popping!

**Comment by Wohlstand** [comment] 2019-01-16 18:36
> It sometimes lags for a while on random occasions

Same happens on my end, but I still not know the reason, however, yeah, why not to run the debug for a long run and check what will happen... But, it's another issue :wink: 

EDIT: Made for that case a new issue #5

**Comment by sneakernets** [comment] 2019-01-17 16:16
Works great on my Galaxy 9, now to try my tablet!

**Comment by sneakernets** [comment] 2019-01-17 16:23
Six chips sometimes has some popping? What's odd is that it's not even the most intense part of the song that causes the pops. Running at PCM Rate seems to help a little bit. 

Midi in question: http://ftp.monash.edu.au/pub/midi.songs/KARAOKE/maninmir.kar

**Comment by Wohlstand** [comment] 2019-01-17 16:25
> Six chips sometimes has some popping? What's odd is that it's not even the most intense part of the song that causes the pops. Running at PCM Rate seems to help a little bit.

This also happens at me (with some other songs), looks like normal behavior because of higher load when playing more notes and activing more chip voices that causing harder logic be processed.

**Comment by Wohlstand** [comment] 2019-01-18 07:09
Anyway, mobile processors aren't so fast and can't guarantee persistent performance like their "big brothers" x86, therefore multichip can be slow when you have choosen too much. At me 5-6 chips can pop, and it's normal because of load.

**Comment by farvardin** [comment] 2019-02-04 22:26
I don't get pop or lag during normal play, but if adlmidi go into background (for example for using an other application while listening to music) then some lag and pops are appearing. 
I suppose it's some android processes for reducing load for background application. I don't know if it worths opening a new issue for this, maybe it's a related problem...

**Comment by Wohlstand** [comment] 2019-02-20 17:57
I think, I'll close this as it's more the individual device issue caused by junk background behaviour out of player itself.

**Closed as completed by Wohlstand** 2019-02-20 17:57 UTC
Labels: help wanted
